# Generated by Django 5.2.1 on 2025-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category_post_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='cacategories',
            field=models.ManyToManyField(related_name='posts', to='posts.category'),
        ),
    ]
