# Generated by Django 5.2.1 on 2025-05-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_categories_post_cacategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cacategories',
            new_name='categories',
        ),
    ]
